"""Generate small deterministic CTD files supported by PyLake."""

import json
import sqlite3
from pathlib import Path

import numpy as np


def profile(depth, offset=0):
    return 21 - 0.25 * depth - 5 / (1 + np.exp(-(depth - 8))) + offset


def write_datalakes(directory, depth):
    times = [0, 600, 1200]
    temperatures = np.column_stack([
        profile(depth, 0),
        profile(depth, -0.2),
        profile(depth, -0.4),
    ])
    payload = {
        "x": times,
        "y": depth.tolist(),
        "z": temperatures.round(3).tolist(),
        "y3": [2.0, 2.2, 2.4],
        "y4": [7.8, 8.0, 8.1],
    }
    (directory / "example_datalakes.json").write_text(
        json.dumps(payload, indent=2),
        encoding="utf-8",
    )


def write_kor(directory, depth):
    header = [
        "KOR MEASUREMENT DATA FILE EXPORT",
        "Synthetic example generated by PyLake",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]
    columns = "DATE (MM/DD/YYYY),TIME (HH:MM:SS),Depth,Temperature"
    rows = [
        f"01/01/2026,00:00:{i:02d},{z:.3f},{t:.3f}"
        for i, (z, t) in enumerate(zip(depth, profile(depth)))
    ]
    (directory / "example_kor.csv").write_text(
        "\n".join(header + [columns] + rows) + "\n",
        encoding="utf-16",
    )


def write_tob(directory, depth):
    lines = [
        "; Sea & Sun CTD example",
        "; Datasets",
        "; columns",
        "; units",
    ]
    for i, (z, temperature) in enumerate(zip(depth, profile(depth)), start=1):
        lines.append(
            f"{i} {z:.3f} {temperature:.3f} 0.40 0.10 0.20 7.2 98.0 9.0 "
            f"01.01.2026 00:00:{i - 1:02d}"
        )
    (directory / "example.tob").write_text(
        "\n".join(lines) + "\n",
        encoding="latin-1",
    )


def write_rsk(directory, depth):
    path = directory / "example.rsk"
    if path.exists():
        path.unlink()
    with sqlite3.connect(path) as connection:
        connection.execute(
            "CREATE TABLE channels (channelID INTEGER, shortName TEXT, "
            "longName TEXT, units TEXT)"
        )
        connection.execute(
            "CREATE TABLE data (tstamp INTEGER, channel01 REAL, channel02 REAL)"
        )
        connection.executemany(
            "INSERT INTO channels VALUES (?, ?, ?, ?)",
            [
                (1, "temp14", "Temperature", "degC"),
                (2, "pres24", "Pressure", "dbar"),
            ],
        )
        connection.executemany(
            "INSERT INTO data VALUES (?, ?, ?)",
            [
                (i * 1000, float(temperature), float(z))
                for i, (z, temperature) in enumerate(zip(depth, profile(depth)))
            ],
        )


def main(output=None):
    directory = Path(output) if output else Path(__file__).parent / "data"
    directory.mkdir(parents=True, exist_ok=True)
    depth = np.linspace(0, 19, 20)
    write_datalakes(directory, depth)
    write_kor(directory, depth)
    write_tob(directory, depth)
    write_rsk(directory, depth)
    return directory


if __name__ == "__main__":
    print(main())
